---
# Most of the information for this role comes from:
#   https://www.csparks.com/BootFedoraZFS/index.md

- name: 'Centos distro must be version 7.{{ centos_minor_version }}.{{ centos_build_version }}'
  fail:
    msg: 'This is Centos {{ ansible_distribution_version }}'
  when: ansible_distribution|lower == 'centos' and ansible_distribution_version != '.'.join(('7', centos_minor_version, centos_build_version))

# - name: Set SELinux to permissive in current session
#   shell: setenforce 0

# - name: Set SELinux to permissive after reboot
#   lineinfile:
#     path: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: 'SELINUX=permissive'

- name: 'Identify the rpm distribution'
  shell: rpm -E %dist
  args:
    warn: false
  register: rpm_dist
  changed_when: false

- name: 'Install epel repo config for CentOS'
  package:
    name: 'epel-release'
  when: ansible_distribution|lower == 'centos'

- name: Install zfs kernel module dependencies
  yum:
    name: '{{ zfs_install_dependencies }}'
  vars:
    zfs_install_dependencies:
      - 'kernel-devel-{{ ansible_kernel }}'
      - 'kernel-headers-{{ ansible_kernel }}'
      - dkms

- name: 'Configure yum to use zfs repo'
  yum:
    name: 'http://download.zfsonlinux.org/epel/zfs-release{{ rpm_dist.stdout }}_{{ centos_minor_version }}.noarch.rpm'
    disable_gpg_check: true
  when: ansible_distribution|lower == 'centos'

- name: Kernel is correct version. Install ZFS packages and dependencies.
  yum:
    name: zfs, zfs-dracut

- name: Copy zmogrify template onto target system
  template:
    src: "{{ role_path }}/templates/zmogrify"
    dest: /usr/local/sbin/
    mode: u=rwx,g=r,o=r

- name: Kernel upgrades should trigger a zfs driver rebuild
  file:
    src: "/usr/local/sbin/zmogrify"
    dest: "/etc/kernel/postinst.d/zmogrify"
    state: link

- name: 'Check if zfs module will load during reboot'
  stat:
    path: /etc/modules-load.d/zfs.conf
  register: zfs_module_loading
  no_log: true
  changed_when: false

- name: 'Configure ZFS kernel Module'
  when: zfs_module_loading.stat.exists == False
  block:
    - name: 'Load zfs module for this session'
      modprobe:
        name: zfs
        state: present

    - name: 'Ensure zfs module is loaded during boot sequence'
      blockinfile:
        path: /etc/modules-load.d/zfs.conf
        create: true
        block: |
          # Load zfs kernel module
          zfs

- name: 'Check if spf module will load during reboot'
  stat:
    path: /etc/modules-load.d/spf.conf
  register: spf_module_loading
  no_log: true
  changed_when: false

- name: 'Configure spf kernel Module'
  when: spf_module_loading.stat.exists == False
  block:
    - name: 'Load spf module for this session'
      modprobe:
        name: spf
        state: present

    - name: 'Ensure spf module is loaded during boot sequence'
      blockinfile:
        path: /etc/modules-load.d/spf.conf
        create: true
        block: |
          # Load spf kernel module to support zfs
          spf

- name: Ensure the zfs services are started during boot
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - zfs-import-cache
    - zfs-import-scan
    - zfs-mount
    - zfs-share
    - zfs-zed
    - zfs.target