---
# Most of the information for this role comes from:
#   https://www.csparks.com/BootFedoraZFS/index.md

- name: 'Centos distro must be version 7.{{ centos_minor_version }}.{{ centos_build_version }}'
  fail:
    msg: 'This is Centos {{ ansible_distribution_version }}'
  when: ansible_distribution|lower == 'centos' and ansible_distribution_version != '.'.join(('7', centos_minor_version, centos_build_version))

# - name: Set SELinux to permissive in current session
#   shell: setenforce 0

# - name: Set SELinux to permissive after reboot
#   lineinfile:
#     path: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: 'SELINUX=permissive'

- name: 'Identify the rpm distribution'
  shell: rpm -E %dist
  args:
    warn: false
  register: rpm_dist
  changed_when: false

- name: 'Install epel repo config for CentOS'
  package:
    name: 'epel-release'
  when: ansible_distribution|lower == 'centos'

- name: Install additional package dependencies
  yum:
    name: 'kernel-devel-{{ ansible_kernel }}, libselinux-python, grub2-efi-x64-modules, gdisk, rpcbind'

- name: 'Install zfs repo config for CentOS'
  package:
    name: 'http://download.zfsonlinux.org/epel/zfs-release{{ rpm_dist.stdout }}_{{ centos_minor_version }}.noarch.rpm'
  when: ansible_distribution|lower == 'centos'

- name: Kernel is correct version. Install ZFS packages and dependencies.
  package:
    name: zfs, zfs-dracut

- name: Copy zmogrify template onto target system
  template:
    src: "{{ role_path }}/templates/zmogrify"
    dest: /usr/local/sbin/
    mode: u=rwx,g=r,o=r

- name: Kernel upgrades should trigger a zfs driver rebuild
  file:
    src: "/usr/local/sbin/zmogrify"
    dest: "/etc/kernel/postinst.d/zmogrify"
    state: link

- name: 'Check if zfs module will load during reboot'
  stat:
    path: /etc/modules-load.d/zfs.conf
  register: zfs_module_loading
  no_log: true
  changed_when: false

- name: 'Load zfs module for this session'
  modprobe:
    name: zfs
    state: present
  when: zfs_module_loading.stat.exists == False

- name: 'Ensure zfs module is loaded during boot sequence'
  blockinfile:
    path: /etc/modules-load.d/zfs.conf
    create: true
    block: |
      # Load zfs kernel module
      zfs

- name: Disable the import cache as it can cause problems as zfs pool changes
  service:
    name: zfs-import-cache
    enabled: true

- name: Enable the import-scan to scan devices
  service:
    name: zfs-import-scan
    enabled: true

- name: Delete unused zfs cache file
  file:
    state: absent
    path: "/etc/zfs/zpool.cache"

- name: rebuild the initramfs excluding the zpool cache
  shell: dracut -fv --kver `uname -r`
