---
# © Awltux Ltd 2019
# Licence: http://www.apache.org/licenses/LICENSE-2.0

# Most of the information for this role comes from:
#   https://www.csparks.com/BootFedoraZFS/index.md

- include_tasks: zfs-install.yml

- include_tasks: zfs-pool.yml

- include_tasks: ansible-audit.yml
