---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos
    box: 'centos/7'
    box_version: '1804.02'
    provider_options:
      gui: false
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["ANSIBLE0012,ANSIBLE0013"]
scenario:
  name: default
  converge_sequence:
    - create
verifier:
  name: testinfra
  lint:
    name: flake8
