#!/bin/bash
# © Awltux Ltd 2019
# Licence: http://www.apache.org/licenses/LICENSE-2.0

set -eu

# Get the current ZFS or SPL module version; they should be the same
modversion=$(dkms status | grep 'zfs\|spl' | tail -n 1 | awk '{ print $2 }' |  sed 's/^\([0-9\.]\+\).*/\1/' | xargs)

echo "Removing existing DKMS modules..."
if ! dkms remove -m zfs -v $modversion --all; then
  echo "ZFS module not present"
fi
if ! dkms remove -m spl -v $modversion --all; then
  echo "SPL module not present"
fi

# FIXME: This could inadvertently delete the wrong module files
rm -rf /lib/modules/*/extra/*
rm -rf /lib/modules/*/weak-updates/*

echo "Reinstalling ZFS and SPL..."
yum reinstall -y spl
yum reinstall -y zfs

echo "Rebuilding DKMS modules..."
dkms add -m spl -v $modversion
dkms add -m zfs -v $modversion

dkms install -m spl -v $modversion
dkms install -m zfs -v $modversion

echo "Loading new modules..."
/sbin/modprobe spl
/sbin/modprobe zfs
